### ISSUE TITLE
`RangeCounterA ` should be `RangeCounterClass` in `src/components/RangeCounterClass.js`

### ISSUE THREAD

**Issue by imjxyang** [mariesta/enzyme-vs-react-testing-library#1]
Hi, thanks for sharing the repo which is quite helpful to understand the difference between `enzyme` and `rtl`.

But I found a little issue in `src/components/RangeCounterClass.js` as the title says.

**Comment by mariesta** [comment]
Very true. Good catch and thank you for bringing it to my attention, @yangjaixi. 🙏 

It's been fixed now.
